export const theme = {
    colors: {
        primary: '#ED8F1D',
        secondary: '#2A4754',
        destructive: '#e33e30',
        background: '#1B2C34',
        backgroundSoft: '#2B4754',
        text: '#FFF',
        textSoft: '#BBB',
        textLight: '#bbb',
        textDark: '#333',
        textLink: '#ED8F1D',
        textLinkHover: '#008B43',
        textLinkActive: '#ED8F1D',
        border: '#848484',
        borderLight: '#ebebeb',
        borderDark: '#aaa',
        borderInput: '#ccc',
        borderInputFocus: '#008B43',
        borderInputError: '#FF0000',
    },
    fontSizes: {
        small: '1.2rem',
        medium: '1.6rem',
        large: '2rem',
        xlarge: '2.4rem',
        xxlarge: '3.2rem',
        xxxlarge: '4.8rem',
    },
    shadows: {
        primary: '0 0 0.5rem #008B4388',
        secondary: '0 0 0.5rem #00427D88',
    },
}
